### ISSUE TITLE
nws5000 rom images/vm clone hdd/boot server vs real nws-3260

### ISSUE THREAD

**Issue by retrohun** [briceonk/news-os#5]
Hi!
Contributing to this mame machine would be hard: https://github.com/briceonk/news-os/blob/master/nws5000x-mame.md
unless having the appropriate dumped rom images! In case without having any legal restrictions, would be handy if they were shared to the public. The reason for this issue: one of my friends owns a different hw, namely a nws-3260 - in order to boot it, there is a need for a preinstalled vm hdd image even for a slightly different nws machine - these steps might accelerate reverse engineering attempts for that portable sony stuff. That machine suffers from several defections, making floppy disk unit and optical drives unusable as a boot device.
Cheers,
retrohun

**Comment by briceonk** [comment]
The ROM images are copyrighted software, so I can't share them, but you might have some luck looking for a full MAME ROM set. The NWS-3260 is also already dumped and emulated in MAME. The main barrier for the 3260 is software - there is no public dump of the installer floppy disk that I am aware of. There are some NEWS-OS 5 tapes on Bitsavers that could probably be extracted to create a bootable hard drive image, but it would not be so straightforward. Unlike NEWS-OS 4, where the images are just tar archives and can be easily extracted (for example, https://github.com/briceonk/news-os/tree/master/src/news-inst), the NEWS-OS 5 installer uses SysV pkgs, so would take more effort to create a usable file system.

**Comment by retrohun** [comment]
Thanks! Close this issue (not an issue).
