### ISSUE TITLE
Could you add more details nws5000x-mame.md about network devices on MAME?

### ISSUE THREAD

**Issue by yoneworld** [briceonk/news-os#6]
Hi, This's Gen Yonezawa.
Thank you useful document.

I'd like to run NEWS-OS on MAME.
I read about https://github.com/briceonk/news-os/blob/master/nws5000x-mame.md

So I have a question.
I installed NEWS-OS 4.2.1aRD on MAME. Install's ok. NEWS-OS is working.
but Network is not working. I'd like to use X-Window.

- Installed MAME on Windows WSL ubuntu
- MAME version is 0.251 for linux
- mame -listnetwork
 Available network adapters
 TAP/TUN Device
- taputil.sh
  taputil.sh yone 192.168.10.40 192.168.10.110 #probably ok

Maybe MAME doesn't connent network adapter.

you said:
```
After starting MAME, make sure to select TAP/TUN device in the Network Devices menu.
 (Press Scroll Lock to disable special key passthrough, then press Tab, then scroll down to Network Devices). 
```
Where is "the Network Devices menu." in MAME?
I can't find "network devices" in "General Setting" and "System Setting". 
Could you add more details where is the "network device" on MAME.

Regards

**Comment by briceonk** [comment]
Thanks for your comment! I'll take a few screenshots later to explain that better. I haven't used MAME with WSL, so I'm not sure if anything is different because of that, but let's see :)

**Comment by briceonk** [comment]
1. Setup TAP/TUN device and launch MAME:
![image](https://user-images.githubusercontent.com/32155223/211217505-81c87c0a-6ce4-40a9-9f27-8e80c06a1803.png)
2. Press Scroll Lock to enable the UI, followed by Tab to bring up the menu
![image](https://user-images.githubusercontent.com/32155223/211217537-396d0d3a-81ff-4c96-a1d5-8aba3e2cc5f3.png)
3. Scroll down to Network Devices and press Enter. If `:sonic` is not mapped to `TAP/TUN Device`, use the left/right arrow keys to select it. You might need to reset MAME after selecting this (it should remember the setting)
![image](https://user-images.githubusercontent.com/32155223/211217628-9bd7117b-00de-49ef-ba26-599f03a001fc.png)
4. Boot to NEWS-OS 4
5. First, log in as `root` and run the following command: `route add default 192.168.5.1 1`, replacing 192.168.5.1 with your system's host address. For you, it would be 192.168.10.110. 
![image](https://user-images.githubusercontent.com/32155223/211217856-54388fcf-c616-4c6f-b034-c3119acc1bfe.png)
7. Next, to test out the basic connection, run `telnet 192.168.10.40` from your host machine.
![image](https://user-images.githubusercontent.com/32155223/211217874-076100fa-8c91-4aed-b577-5006c3e44a28.png)
8. If that works, run `sxdm` from the root console or telnet session to start the NEWS Desk window manager
![image](https://user-images.githubusercontent.com/32155223/211217918-27d4f93c-9ea3-4866-942e-d8891d04f813.png)
9. Finally, connect to the emulated system using Xephyr. 
![image](https://user-images.githubusercontent.com/32155223/211217990-75fabc90-58ab-4b13-899b-8c2c8c9da1fc.png)
10. In the screen that pops up, you should see the NEWS Desk login prompt:
![image](https://user-images.githubusercontent.com/32155223/211218045-4e0c0fda-7b6a-4bf5-982d-8ccf81223712.png)

For Japanese fonts to work, you'll need to copy them from NEWS-OS (NEWS-OS's `/usr/lib/X11/fonts/100dpi` and friends) to your host machine and add them to the font path. You may need to do some additional work on the font directories depending on your distro. Check out https://github.com/briceonk/news-os/blob/master/src/xdmcp.py for a wrapper script I wrote for connecting to XDMCP servers with font path manipulation included.

**Comment by yoneworld** [comment]
Dear briceonk
Thank you very much! I telneted from WSL to NEWS on MAME. Network is working. 

## Network is working!
![image](https://user-images.githubusercontent.com/2682671/211246067-cb04d235-29c5-4614-996c-92175ea3215f.png)

I found nws5000x.cfg for MAME should be like that
```
sonic interface =0"
```

```
<?xml version="1.0"?>
<!-- This file is autogenerated; comments and unknown tags will be stripped -->
<mameconfig version="10">
    <system name="nws5000x">
        <image_directories>
            <device instance="floppydisk" directory="" />
            <device instance="harddisk" directory="" />
            <device instance="cdrom" directory="" />
        </image_directories>
        <input>
            <keyboard tag=":hid" enabled="1" />
        </input>
        <network>
            <device tag=":sonic" interface="0" mac="00:00:00:00:00:00" />
        </network>
    </system>
</mameconfig>
```

## I have a question.
And then unfortunatelly I can't connnect X-Window. 
I typed on NEWS. it looks working.
```
sxdm
```

I typed that on WSL.
```
Xephyr -ac -query 192.168.10.40 -screen 1024x768x8 :2
```
just Opened Black Screen.  No Login Prompt.

Should I set any other thing?
```
export DISPLAY=:2.0
```
etc....

Thank you.
Regards

**Comment by briceonk** [comment]
Yonezawa-san,
Cool, I'm glad networking is working, that is a big part of the battle done! Can you confirm that `sxdm` is actually running on the emulated NEWS system with `ps`? If so, try killing `sxdm`, then relaunching it. I don't see it often, but I have seen a case in the past where `sxdm` refused to respond to any queries. Make sure you leave Xephyr on the black screen for a little while - since the driver can only run at a certain % of real-time speed, the login window can take some time to pop up depending on your host system's performance. Even my i9-12900K system can only achieve 30-35% speed when using SCSI and Ethernet.
Also, I didn't see your confirmation, but if you didn't set the default route, XDMCP won't work. `telnet` seems to be able to handle it, for some reason, but I wasn't able to get X working without setting the default route.

Finally, if restarting `sxdm` and confirming the default route doesn't fix it, I'd recommend using a tool like `wireshark` to see what the emulated system is kicking back to Xephyr's XDMCP request - if there are networking issues, those will hopefully show up. You could also try running plain old `xdm` to see if it has any difference in behavior compared to `sxdm`.

- Brice

**Comment by yoneworld** [comment]
Dear briceonk
I got it !! Thank you very much!!!
![image](https://user-images.githubusercontent.com/2682671/211804382-a7de46c4-fa2b-47db-afab-83d18642925c.png)
![newswork2](https://user-images.githubusercontent.com/2682671/212049202-942a4509-e27f-4d95-966e-e78d9bf2c057.png)

Japanese Fonts work!
![image](https://user-images.githubusercontent.com/2682671/213859375-3c70157d-bd37-4f90-8c30-ab4e9fb9680c.png)

**Comment by briceonk** [comment]
Yonezawa-san,
Great! I am happy it worked. I'll add the extra details to the document later. If there is anything else you think I should add, please let me know :) 

- Brice

**Comment by yoneworld** [comment]
#### NEWS-OS 4.2.1R Booting movie
https://www.youtube.com/watch?v=L89Jbi8ibA8

#### NEWS-OS 4.2.1R X-Window Operation movie
https://www.youtube.com/watch?v=TvFyzIpglKE

**Comment by briceonk** [comment]
Awesome!! Thanks for sharing!
